### ISSUE TITLE
exceded the number of child0 script variables error after playing for a while?!

### ISSUE THREAD

**Issue by theminecraften66** [ineedbots/piw5_bot_warfare#72]
so i will play sagotage on any map and after about three to five matches back to back it freezes the game and i have to press the windows key and it has this error in a little box next to the launcher on the taskbar at the bottom of the windows screen

**Comment by ineedbots** [comment]
https://github.com/ineedbots/piw5_bot_warfare/blob/master/raw/maps/mp/bots/_bot_script.gsc#L56
Its because of the challenge processing, it uses too much variable.  It fine when bots are processing challenges one by one, but when a round changes, they do it all at once.

https://github.com/chxseh/MW3-GSC-Dump/blob/main/_wii-gsc-dump/maps/mp/gametypes/_missions.gsc#L2631

**Comment by ineedbots** [comment]
https://github.com/ineedbots/piw5_bot_warfare/commit/6a5af7d510b336b5ba3d377cdb172eaffd72d1d0
should fix this

**Comment by theminecraften66** [comment]
thanks for this love the mod but it kinda kills the mood when binge playing it and it crashes

**Comment by theminecraften66** [comment]
also should fix what?
