### ISSUE TITLE
Crashing issue with ported maps

### ISSUE THREAD

**Issue by Juggernaut369** [ineedbots/piw5_bot_warfare#77]
Are any of the custom maps ported from other COD's on Plutonium's site compatible with Bot Warfare? I've played most of the original and dlc maps that came with MW3 and have had no issues using Bot Warfare. However, every custom map that's been ported over gives me a direct x crash within 2 or 3 minutes of starting a match with bots (DirectX has encountered and unrecoverable error), and this is whether I've added my own waypoints or not. I can run around in the waypoint editor for hours and it won't crash. I don't think my hardware is the issue, but if needed, I have a 3700X CPU and a 2070Super GPU with 32 gigs of Ram.

**Comment by Resxt** [comment]
@Juggernaut369 It depends of what you mean by compatible.

Yes custom maps work, yes bots can have waypoints for them and play normally if you give them the right waypoints, no they won't play normally on custom maps if you don't add waypoints ([covered here](https://github.com/ineedbots/piw5_bot_warfare/blob/master/raw/bw-assets/wpedit.md))

As for the crashes I believe it's not really a Bot Warfare issue but most likely a Modern Warfare 3 issue.
I had the same issue on several maps in the past, I even had to remove some of them from my servers.
It seems like Plutonium is working on fixing those issues on the testing version so keep an eye on the updates.

**Comment by Juggernaut369** [comment]
Thanks for the reply. I’ll keep an eye on any plutonium updates. I was planning on adding waypoints to most of the ported maps, however I stopped after experiencing the Dx crash on Bailout and Trailerpark. Only reason I thought it might be related to bot warfare was because it only happens when I load the bots. Maps work fine with just me running around. Thanks again.

**Comment by Resxt** [comment]
@Juggernaut369 I can tell you that I've been playing multiple games on both of these maps on the testing version and didn't experience any crash.

Also what you need to keep in mind is that ported maps are ported by "random" people. Sometimes there are issues on their maps that they didn't fix.
For example Bailout had a crash issue even on the testing version. This was because the person who ported it ported it with issues and didn't find them/fix them. He gave me an updated and fixed version which stopped the crashes.

Don't expect maps to be perfect unless you know who ported it and they confirmed it's a final and bug free version.

As for why it crashes with Bot Warfare what I understood after weeks of testing is that:
- No matter if they're bots 18 players will use more memory and CPU, which can cause issues due to how old the game is and the memory limitations it has (better in the testing version)
- Bots will go in a lot of spots on the map so they might find areas that crashes the game that you didn't find or shoot a barrel that crashes the game. In that case it's not related to the bots, it's just a map issue

What I usually do is have 18 bots play an entire domination or demolition game to see if the game crashes. If it does then most likely they found an area or item that crashes the game. That's how I found that the cars on the A bomb site on Bailout crashed the game after they exploded.

Finally for the waypoints just in case you don't know you can simply re-use waypoints from the other Bot Warfare repositories. You don't need to create them.

**Comment by Juggernaut369** [comment]
@Resxt Thanks for all the useful information. Question, unless I'm looking in the wrong place, the waypoints in the other Bot Warfare repositories are all in .csv format. Where do I put the .csv, or could you point me to what I need to convert it to .gsc?

**Comment by Resxt** [comment]
@Juggernaut369 I don't know how to use CSV files, I'm looking for this too. But for some COD games there are GSC files, just need to look in the right folder
[MW2](https://github.com/ineedbots/iw4x_bot_warfare/tree/master/userraw/maps/mp/bots/waypoints)  [COD 4](https://github.com/ineedbots/cod4x_bot_warfare/tree/master/main_shared/maps/mp/bots/waypoints) 

If you wanna talk more add me on Discord (check my GH profile) since we're out of topic now

**Comment by Juggernaut369** [comment]
Thanks again
